window.OCEAN_MISSIONS = [
  {
    id: "m01",
    chapter: "第一章｜認識洋流",
    title: "箭頭會說話",
    story: "海洋研究站遺失了一個感測器。請從臺灣東南方投放漂流瓶，順著主要洋流抵達綠島東北方的回收區。",
    difficulty: 1,
    start: { lat: 20.8, lon: 121.7, label: "巴士海峽北側" },
    target: { lat: 23.7, lon: 123.0, label: "綠島東北海域", radiusKm: 115 },
    month: 7,
    allowedMonths: [5, 6, 7, 8, 9],
    maxDays: 12,
    maxDepth: 10,
    recommendedDepth: 0,
    rules: ["順流入門", "12 天內", "深度 0–10 m"],
    tip: "先找出往北的快速流帶。洋流箭頭的方向，比目的地的直線方向更重要。",
    successText: "你抓到臺灣東側北上的流帶，成功讓漂流瓶順流抵達目標。",
    failText: "漂流瓶沒有進入主要北向流帶。試著觀察起點東側的箭頭方向。"
  },
  {
    id: "m02",
    chapter: "第一章｜認識洋流",
    title: "黑潮高速公路",
    story: "研究團隊要把訊息送到琉球。利用臺灣東側較快的北向洋流，讓漂流瓶抵達石垣島附近。",
    difficulty: 1,
    start: { lat: 22.1, lon: 122.2, label: "蘭嶼東南方" },
    target: { lat: 24.4, lon: 124.2, label: "石垣島南方", radiusKm: 125 },
    month: 6,
    allowedMonths: [4,5,6,7,8,9,10],
    maxDays: 16,
    maxDepth: 30,
    recommendedDepth: 10,
    rules: ["利用快速流", "16 天內", "可使用海錨"],
    tip: "流速快不代表一定會命中目標。接近目標時，可用海錨降低速度。",
    successText: "你先利用快速洋流前進，再控制速度進入回收區。",
    failText: "可能是速度太快而錯過目標，或投放後沒有進入主要流帶。"
  },
  {
    id: "m03",
    chapter: "第二章｜季節挑戰",
    title: "海峽的季節密碼",
    story: "一艘研究船在澎湖西南方投放漂流瓶。請選擇適合的月份，讓它往臺灣海峽北部漂流。",
    difficulty: 2,
    start: { lat: 22.4, lon: 118.8, label: "澎湖西南海域" },
    target: { lat: 25.2, lon: 120.1, label: "臺灣海峽北部", radiusKm: 130 },
    month: 7,
    allowedMonths: [1,4,7,10],
    maxDays: 22,
    maxDepth: 30,
    recommendedDepth: 0,
    rules: ["比較季節", "22 天內", "月份可調"],
    tip: "夏季與冬季的季風不同，臺灣海峽附近的表層漂流方向也可能不同。",
    successText: "你選對季節，讓漂流瓶搭上往北的海峽流況。",
    failText: "季節可能不適合。比較 1 月與 7 月的箭頭方向，再重新投放。"
  },
  {
    id: "m04",
    chapter: "第二章｜季節挑戰",
    title: "冬季逆風任務",
    story: "冬季東北季風增強。請調整小帆與海錨，避免漂流瓶被風推離臺灣東北角的觀測站。",
    difficulty: 2,
    start: { lat: 24.2, lon: 122.8, label: "宜蘭外海" },
    target: { lat: 26.0, lon: 124.4, label: "東海觀測區", radiusKm: 120 },
    month: 1,
    allowedMonths: [1,2,11,12],
    maxDays: 18,
    maxDepth: 30,
    recommendedDepth: 10,
    rules: ["冬季限定", "風力明顯", "控制小帆"],
    tip: "漂流瓶露出海面的面積越大，受到風的影響越明顯。必要時縮小帆面積。",
    successText: "你降低風力影響，讓洋流成為主要推進力量。",
    failText: "漂流瓶受到的風力太強。縮小帆面積，或下降到 10 公尺再試一次。"
  },
  {
    id: "m05",
    chapter: "第三章｜深度挑戰",
    title: "潛入另一條流",
    story: "海面的風把漂流瓶推向錯誤方向。請下降到較深水層，找出更適合的洋流。",
    difficulty: 2,
    start: { lat: 23.0, lon: 126.2, label: "琉球南方海域" },
    target: { lat: 27.2, lon: 129.0, label: "沖繩東南方", radiusKm: 135 },
    month: 4,
    allowedMonths: [3,4,5],
    maxDays: 23,
    maxDepth: 50,
    recommendedDepth: 30,
    rules: ["深度必須 ≥ 30 m", "電量有限", "23 天內"],
    requireDepth: 30,
    tip: "不同深度的水流不一定相同。每次調整深度都會消耗探測器電量。",
    successText: "你找到次表層較合適的流向，避開海面的不利風況。",
    failText: "這一關需要利用 30 公尺以下的水層。觀察切換深度後箭頭的變化。"
  },
  {
    id: "m06",
    chapter: "第三章｜深度挑戰",
    title: "上下切換",
    story: "先在表層快速北上，再於接近九州時下降減速。你只有三次調整深度的機會。",
    difficulty: 3,
    start: { lat: 24.5, lon: 125.0, label: "宮古島東方" },
    target: { lat: 30.0, lon: 130.2, label: "九州南方", radiusKm: 145 },
    month: 8,
    allowedMonths: [6,7,8,9],
    maxDays: 30,
    maxDepth: 50,
    recommendedDepth: 0,
    depthChangeLimit: 3,
    rules: ["最多調深 3 次", "先快後慢", "30 天內"],
    tip: "把深度當作換車：表層快速前進，靠近目標後再切換較慢的水層。",
    successText: "你成功利用不同深度控制速度與方向。",
    failText: "檢查深度切換時機：太早下降會變慢，太晚下降可能錯過目標。"
  },
  {
    id: "m07",
    chapter: "第四章｜颱風任務",
    title: "颱風外圍借力",
    story: "一個教學颱風正在菲律賓東方北上。利用外圍流況改變方向，但不要讓漂流瓶進入危險核心。",
    difficulty: 3,
    start: { lat: 18.8, lon: 126.0, label: "呂宋島東方" },
    target: { lat: 23.4, lon: 132.6, label: "沖繩海槽東南端", radiusKm: 185 },
    month: 9,
    allowedMonths: [7,8,9,10],
    maxDays: 18,
    maxDepth: 50,
    recommendedDepth: 0,
    typhoon: {
      name: "教學颱風・海燕",
      startDay: 2,
      endDay: 10,
      dangerRadiusKm: 120,
      influenceRadiusKm: 620,
      track: [
        [17.0, 124.0], [18.5, 124.8], [20.1, 125.6], [21.8, 126.2],
        [23.5, 126.7], [25.4, 127.3], [27.5, 128.1], [29.4, 129.4], [31.0, 131.0]
      ]
    },
    rules: ["颱風事件", "避開核心", "18 天內"],
    tip: "颱風不是推進按鈕。靠得太近會任務失敗；在外圍才可能獲得方向改變。",
    successText: "你利用颱風外圍的額外流況轉向，同時避開危險核心。",
    failText: "可能太接近颱風核心，或沒有在正確時間進入外圍影響區。"
  },
  {
    id: "m08",
    chapter: "第四章｜颱風任務",
    title: "下潛避風",
    story: "颱風即將通過臺灣東方。請在強風接近時下降，通過後再回到表層前進。",
    difficulty: 3,
    start: { lat: 21.5, lon: 123.8, label: "臺灣東南外海" },
    target: { lat: 26.4, lon: 127.4, label: "沖繩西南方", radiusKm: 145 },
    month: 8,
    allowedMonths: [7,8,9],
    maxDays: 24,
    maxDepth: 50,
    recommendedDepth: 30,
    typhoon: {
      name: "教學颱風・白鷺",
      startDay: 4,
      endDay: 12,
      dangerRadiusKm: 110,
      influenceRadiusKm: 680,
      track: [
        [19.5, 128.5], [20.3, 127.5], [21.3, 126.6], [22.5, 125.8],
        [23.8, 125.3], [25.0, 125.5], [26.4, 126.3], [28.1, 127.7], [30.0, 129.8]
      ]
    },
    rules: ["颱風事件", "建議下潛", "24 天內"],
    tip: "風對海面附近的漂流物影響較大。下降後，風力修正會明顯減弱。",
    successText: "你在颱風靠近時下潛避開強風，再回到適合的水層完成任務。",
    failText: "嘗試在颱風接近前下降到 30 或 50 公尺，通過後再回到表層。"
  },
  {
    id: "m09",
    chapter: "第五章｜生態夥伴",
    title: "海龜導航員",
    story: "保育團隊要追蹤海龜常用的暖水流帶。進入海龜活動區後，可啟動一次導航協助。",
    difficulty: 2,
    start: { lat: 20.5, lon: 122.6, label: "巴士海峽東側" },
    target: { lat: 25.2, lon: 126.8, label: "琉球南部", radiusKm: 145 },
    month: 6,
    allowedMonths: [5,6,7,8,9],
    maxDays: 26,
    maxDepth: 30,
    recommendedDepth: 10,
    animal: { type: "turtle", label: "海龜導航", icon: "🐢", durationDays: 4, strength: 0.24 },
    rules: ["海龜夥伴", "一次協助", "26 天內"],
    tip: "海龜常利用洋流節省移動能量；遊戲中的『搭乘』是象徵性表現。",
    successText: "你進入適合海龜移動的流帶，並善用一次導航協助。",
    failText: "先順著暖水流帶靠近海龜活動區，再啟動導航協助。"
  },
  {
    id: "m10",
    chapter: "第五章｜生態夥伴",
    title: "鯨魚長途列車",
    story: "鯨群正沿著季節性路徑北上。選對月份並靠近遷徙走廊，可獲得一段長距離協助。",
    difficulty: 3,
    start: { lat: 23.6, lon: 128.5, label: "琉球東南方" },
    target: { lat: 31.0, lon: 132.9, label: "日本南方海域", radiusKm: 210 },
    month: 4,
    allowedMonths: [3,4,5,10,11],
    maxDays: 38,
    maxDepth: 50,
    recommendedDepth: 10,
    animal: { type: "whale", label: "跟隨鯨群", icon: "🐋", durationDays: 8, strength: 0.42 },
    rules: ["鯨魚夥伴", "季節限定", "38 天內"],
    tip: "選擇春季北上月份較容易遇到鯨群；秋季可能出現相反的遷徙方向。",
    successText: "你選對季節，利用鯨群遷徙走廊完成長距離漂流。",
    failText: "檢查月份是否符合北上遷徙，再尋找洋流與鯨群路徑重疊的位置。"
  },
  {
    id: "m11",
    chapter: "第六章｜綜合挑戰",
    title: "研究浮標救援",
    story: "一枚研究浮標失去動力，漂流瓶必須把備用定位器送到目標區。你需要同時管理季節、深度與電量。",
    difficulty: 3,
    start: { lat: 19.2, lon: 121.5, label: "呂宋海峽" },
    target: { lat: 29.0, lon: 129.2, label: "奄美群島東方", radiusKm: 210 },
    month: 7,
    allowedMonths: [1,4,7,10],
    maxDays: 42,
    maxDepth: 50,
    recommendedDepth: 10,
    depthChangeLimit: 4,
    rules: ["綜合挑戰", "調深 4 次", "42 天內"],
    tip: "先規劃整體路線，再決定在哪些位置調整深度，不要頻繁消耗電量。",
    successText: "你整合季節、洋流與深度判讀，成功完成研究浮標救援。",
    failText: "查看軌跡偏離的位置，重新思考月份與深度切換策略。"
  },
  {
    id: "m12",
    chapter: "自由模式",
    title: "自由漂流實驗室",
    story: "自由測試不同月份與深度。沒有唯一正確答案，觀察同一起點在不同條件下會漂到哪裡。",
    difficulty: 1,
    start: { lat: 22.0, lon: 122.0, label: "自訂實驗起點" },
    target: { lat: 29.0, lon: 131.0, label: "自訂觀察目標", radiusKm: 180 },
    month: 7,
    allowedMonths: [1,2,3,4,5,6,7,8,9,10,11,12],
    maxDays: 60,
    maxDepth: 50,
    recommendedDepth: 0,
    freeMode: true,
    animal: { type: "turtle", label: "實驗協助", icon: "🐢", durationDays: 4, strength: 0.22 },
    rules: ["自由實驗", "60 天", "所有設定開放"],
    tip: "記錄每次的月份、深度與路線，像科學家一樣比較不同實驗條件。",
    successText: "你完成了一次自由漂流實驗。比較不同條件，找出最穩定的路線。",
    failText: "自由模式不以失敗為終點。查看路線後，修改一個條件再比較。"
  }
];
